/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.occ.matsu;  
@SuppressWarnings("all")
public enum ByteOrder { 
  LittleEndian, BigEndian, NativeEndian, IgnoreEndian  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ByteOrder\",\"namespace\":\"org.occ.matsu\",\"symbols\":[\"LittleEndian\",\"BigEndian\",\"NativeEndian\",\"IgnoreEndian\"]}");
}
